# version: 2.1

# orbs:
#   aws-ecr: circleci/aws-ecr@9.0.1

# executors:
#   basic:
#     docker:
#       - image: cimg/base:stable

# jobs:
#   say-hello:
#     executor: basic
#     steps:
#       - checkout
#       - run:
#           name: 'Say hello'
#           command: 'echo Hello, World!!!!!'
#       - run:
#           name: get Message
#           command: echo "export GIT_COMMIT_MESSAGE=\"$(git log --format=%B -n 1 $CIRCLE_SHA1)\"" >> $BASH_ENV
#       - run:
#           name: get Message
#           command: echo $GIT_COMMIT_MESSAGE
#       - run: |
#           cp $BASH_ENV bash.env
#       - persist_to_workspace:
#           root: .
#           paths:
#             - bash.env
#   checkeee:
#     executor: basic
#     steps:
#       - checkout
#       - attach_workspace:
#           at: .
#       - run: |
#           cat bash.env >> $BASH_ENV
#       - run:
#           name: 'Say hello'
#           command: 'echo $GIT_COMMIT_MESSAGE'

# workflows:
#   say-hello-workflow:
#     jobs:
#       - say-hello
#       - checkeee:
#           requires:
#             - say-hello
#       - aws-ecr/build-and-push-image:
#           requires:
#             - say-hello
#           context: aws-dev
#           dockerfile: Dockerfile
#           path: .
#           repo: cyber/non/test
#           tag: '0.0.3'
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

executors:
  basic:
    docker:
      - image: cimg/base:stable

jobs:
  say-hello:
    executor: basic
    steps:
      - checkout
      - run:
          name: 'Say hello'
          command: 'echo Hello, World!!!!!'
      - run:
          name: get Message
          command: echo "export GIT_COMMIT_MESSAGE=\"$(git log --format=%B -n 1 $CIRCLE_SHA1)\"" >> $BASH_ENV
      - run:
          name: get Message
          command: echo $GIT_COMMIT_MESSAGE
      - run: |
          cp $BASH_ENV bash.env
      - persist_to_workspace:
          root: .
          paths:
            - bash.env
  checkeee:
    # executor: basic
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - attach_workspace:
          at: .
      - run: |
          cat bash.env >> $BASH_ENV
      - run:
          name: 'Say hello'
          command: 'echo $GIT_COMMIT_MESSAGE'
      - aws-ecr/build-and-push-image:
          attach-workspace: true
          dockerfile: Dockerfile
          # path: .
          repo: cyber/non/test
          tag: $GIT_COMMIT_MESSAGE
    # steps:
    #   - checkout
    # - attach_workspace:
    #     at: .
    #   - run: |
    #       cat bash.env >> $BASH_ENV
    #   - run:
    #       name: 'Say hello'
    #       command: 'echo $GIT_COMMIT_MESSAGE'

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - checkeee:
          requires:
            - say-hello
          context: aws-dev
      # - build-push:
      #     machine:
      #       image: ubuntu-2204:2022.07.1
      #     steps:
      #       - run: |
      #           cat bash.env >> $BASH_ENV
      #       - run:
      #           name: 'Say hello'
      #           command: 'echo $GIT_COMMIT_MESSAGE'
      #       - aws-ecr/build-and-push-image:
      #           requires:
      #             - say-hello
      #           attach-workspace: true
      #           context: aws-dev
      #           dockerfile: Dockerfile
      #           path: .
      #           repo: cyber/non/test
      #           tag: $GIT_COMMIT_MESSAGE

      # - aws-ecr/build-and-push-image:
      #     requires:
      #       - say-hello
      #     attach-workspace: true
      #     context: aws-dev
      #     dockerfile: Dockerfile
      #     path: .
      #     repo: cyber/non/test
      #     tag: $GIT_COMMIT_MESSAGE
