version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

executors:
  basic:
    docker:
      - image: cimg/base:stable

jobs:
  setup-env:
    executor: basic
    steps:
      - checkout
      - run:
          name: Get message
          command: echo "export GIT_COMMIT_MESSAGE=\"$(git log --format=%B -n 1 $CIRCLE_SHA1)\"" >> $BASH_ENV
      - run: |
          cp $BASH_ENV bash.env
      - persist_to_workspace:
          root: .
          paths:
            - bash.env
  build-and-push:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          cat bash.env >> $BASH_ENV
      - run:
          name: 'Check environment git commit message'
          command: 'echo $GIT_COMMIT_MESSAGE'
      - aws-ecr/build-and-push-image:
          attach-workspace: true
          dockerfile: Dockerfile
          path: .
          repo: cyber/non/test
          tag: $GIT_COMMIT_MESSAGE

workflows:
  build-console-ui-workflow:
    jobs:
      - setup-env:
          filters:
            branches:
              only:
                - develop
      - build-and-push:
          requires:
            - setup-env
          context: aws-dev
